server:
  port: 8088
  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:mysql://47.98.238.150/my-test?useSSL=false&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: shi974075295
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 47.98.238.150
    port: 6379
    password: shi974075295

  data:
    mongodb:
      uri: mongodb://tester:shi974075295@47.98.238.150:27017/test

  rabbitmq:
    addresses: 47.98.238.150:5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /

mybatis:
  type-aliases-package: com.my.test.demo.entity
  mapper-locations: classpath:mapper/*.xml
